### ISSUE TITLE
Tiles are stretched in build area projects

### ISSUE THREAD

**Issue by jhenshall** [mapswipe/mapswipe#114]
For build area projects on iPhone, tiles are stretched vertically to fill the screen and therefore do not line up properly. It seems the bottom two tiles are square, the top 4 stretched especially on longer screens (e.g. iPhone X, XS, 11 Pro).

Perhaps as a result, the known alignment issue seems particularly bad.

Screenshot attached.

![IMG_2537-small](https://user-images.githubusercontent.com/6359748/65691983-b4bd3f00-e069-11e9-9f68-3d5349eb887d.png)

**Comment by laurentS** [comment]
This should be fixed in 2293dc71adc0, with the limitation that for very wide screens, the imagery will display more than 2 columns, something like the screenshot below. Note the 3rd column (highlighted in red/yellow for clarity). As the user scrolls, the images snap to the left side of the screen, so it is completely usable, it just looks a bit strange at first.
I don't think there are many phones this wide (the screenshot is from an emulator with exagerated dimensions), so in practice, it's unlikely that anyone will really notice. But writing this down for reference...
![Screenshot_1569543655](https://user-images.githubusercontent.com/1745184/65733241-a56bdf00-e0c5-11e9-803c-29610db22b19.png)
