### ISSUE TITLE
Swipe up/down is difficult on some phones

### ISSUE THREAD

**Issue by Birnbaum2001** [mapswipe/mapswipe#127]
Hi,

The new version offers swipe up/down to mark all 6 tiles as red or undo this. This doesn't work on IOS. The hint is shown, but nothing is marked.

Tested on iPhone XS with IOS 12.4 and 13.1 (upgrade didn't help obviously :) )

Cheers,
Birnbaum2001

----
edited the title, as it does work, just not as easy as I thought :)

**Comment by laurentS** [comment]
Hi @Birnbaum2001 
thanks for reporting this issue.
The swipe needs to be quite long, specifically, more than one tile vertically, for it to work. We might need to shorten that distance, but can you double check with this in mind, and let me know if you're still seeing the problem?
Cheers,
Laurent

**Comment by jhenshall** [comment]
Hi @Birnbaum2001 - worth noting that it is also very sensitive to any horizontal movement, which ends up cancelling the action. @laurentS - agree maybe a shorter swipe? Or can we have more horizontal tolerance (if that makes sense)?

**Comment by jhenshall** [comment]
We've also had feedback that users are being prevented from swiping because the help text to swipe down and mark all 6 red is appearing instead. Perhaps this ticket should be a broader look at the swipe down for 6 red function?

**Comment by Birnbaum2001** [comment]
Thanks for the quick feedback. You are right, it works when swiping more than one tile in height and very carefully to not trigger horizontal swipe. More tolerance or shorter vertical swipe could indeed help here.

Cheers,
Birnbaum2001

**Comment by laurentS** [comment]
Also see #132 for a wider discussion...
It sounds like we should make the required vertical "travel" shorter, and find a way to make left/right swiping a bit less sensitive.
I need to look into how the swipe event is captured by the various components.

**Comment by Birnbaum2001** [comment]
Hi @laurentS,

thanks for the adjustment. It's easier now but still not going smooth. It seems that the necessary height for a swipe down/up is about one tile. I think half a tile would suffice. At least for me (iPhone XS). Might be different on other phones especially with smaller screens. 

Additionally, it's still quite easy to trigger a horizontal swipe and cancel the swipe down/up. The tolerance could still be increased (if you did already). 

Cheers,
Birnbaum2001

**Comment by laurentS** [comment]
Ok, I think I might have figured the reason why you're seeing this. If you're using an iPhone XS, the screen is much longer than an "average" phone, so the tiles were distorted and I fixed this in #114, but I didn't fix the same bug for this swipe movement.
The bug is [here](https://github.com/mapswipe/mapswipe/blob/08614973692b36e7dda3c2e9b6ed1954090826e1/src/shared/views/Mapper/IndividualCard.js#L149) (and on line 151 below) and it can be fixed by replacing `TILE_VIEW_HEIGHT` with `TILE_SIZE` from the [Globals.js](https://github.com/mapswipe/mapswipe/blob/08614973692b36e7dda3c2e9b6ed1954090826e1/src/shared/Globals.js#L30) file.

@Birnbaum2001 seeing that you have managed to setup the dev environment, do you want to submit your first PR with that fix? :)

**Comment by Birnbaum2001** [comment]
I may give it a try next :)

**Comment by laurentS** [comment]
@Birnbaum2001 this should now be fixed in 2.0.2. Can you check and close this issue if you're happy with the fix?

**Comment by Birnbaum2001** [comment]
Thanks, I think it's easier now but not perfect yet. It's still quite easy to trigger a horizontal pan and the distance feels quite large. And given that a large distance needs to be covered, you easily trigger the horizontal pan, which cancels the vertical one.

Regarding the distance, I compare it always with twitter, I think. If you watch images in the twitter app, you can close them by doing a small swipe down. Just like one thumb in height. Everything larger yields in work :)

But in the end, I don't want to overcomplicate things. If I'm the only one, it's fine like it is :)

**Comment by oiva** [comment]
Sorry to piggyback on this issue, but is there any possibility to avoid "all red" situations automatically? I've seen groups where all tiles are the "no imagery" tile (white background with the camera icon), especially in the recent "Economic development - Philippines (4)". It's a bit frustrating to swipe through these even though the down swipe makes a bit easier.

**Comment by laurentS** [comment]
> But in the end, I don't want to overcomplicate things. If I'm the only one, it's fine like it is :)

@Birnbaum2001 my take on this is that for one user who took the time to report the problem, there are probably hundreds who don't bother, but are still affected by the problem. I would agree with you that it's not 100% easy to swipe down, so we can still do better.
Let's see if we can reduce that swiping distance even further. Also, I think there might be a way to disable the left/right swipe as soon as the touch has travelled even minimally downwards, that might make it easier. I'll give it a try, but if you have any ideas on how to achieve this, please share them here :)

**Comment by laurentS** [comment]
@oiva I can think of a few options to prevent such issues. I just did a couple of groups like that yesterday, where the entire group was clouds, all white. They are a bit frustrating indeed.

1. when creating projects, project managers could go through the imagery, and have some way to marking cloudy areas as "bad imagery", so that users don't see them. Unfortunately, I think that would create a big bottle neck in maintaining the list of projects. And it would require substantial additions to the backend code.
2. if there is indeed no imagery for a tile, the app could automatically mark it red. That would cover the "no imagery" icon, but not the "all white" tiles. Dealing with this latter case is probably a lot harder, as we would need to compute how much percentage of the tile is white, and if it's over X%, we mark it red. (the user could then change it as they please, it would only be a starting "suggestion")
3. I think that if we can make the swipe much easier, as @Birnbaum2001 suggests, these groups may not be that bad. 

I would start by fixing 3., then if it's still annoying, look into 2. @oiva what do you think? feel free to open a separate ticket for this issue, and we can gather ideas there.

@Hagellach37 might have some further ideas as well.

**Comment by oiva** [comment]
@laurentS Thanks! This was specifically case 2: no imagery for a tile. There were multiple groups without any imagery which would have been nice to skip or automatically mark red.

I agree that detecting cloudy tiles would be a lot harder to do and the cloud case is probably suitably covered by a better swipe down.

I can open a separate ticket about detecting tiles with no imagery.

**Comment by lukasbisdorf** [comment]
Hi, I have the same issue again on iOS 13 with an iPhone XS. 
It is not possible to mark tiles with a swipe down - maybe the threshold for left / right is too small. 

It works sometimes, but only with a real precise move.

**Comment by Maijin** [comment]
Same problem on iPhone 11

**Comment by laurentS** [comment]
@Birnbaum2001 @Maijin @lukasbisdorf I have released a test version of the app that should fix this problem. I would love it if you could try it out and let me know if it works better for you. Instructions to install the test app are [here](https://github.com/mapswipe/mapswipe/blob/deaf83f4cf969628c87f993333fd6ada62b183b1/docs/test_dev_version.md). Please use version `2.0.3(4)-beta`.
Thanks for your help!

**Comment by Birnbaum2001** [comment]
works smooth now. Thanks :)

**Comment by laurentS** [comment]
Fixed in release 2.0.4. If you are still seeing the problem, please reopen this ticket and comment here.

**Comment by Maijin** [comment]
Yeah much better now, the tutorial also better.
