### ISSUE TITLE
Mark all 6 tiles green

### ISSUE THREAD

**Issue by jhenshall** [mapswipe/mapswipe#132]
Is there a way we could have functionality to mark all tiles green. Like with swipe down to mark all red?

**Comment by laurentS** [comment]
It would be cool to add indeed. The rationale for adding the "swipe to red" option was user feedback, where many complained that tapping 18 times on each screen fully covered in clouds was super annoying, to the point where many gave up on mapping.

Looking at it purely rationally, 6 taps for "all green" is not that bad, but mostly, I can't think of a good motion for green :)

**Comment by jhenshall** [comment]
Yeah, I agree. 6 taps doesn't feel that bad and I can't think of a more efficient motion. Maybe pinch? Will need user testing! Leave open for a while incase anyone has any suggestions?

**Comment by Birnbaum2001** [comment]
I thought of something similar: swipe down marks red, swipe up marks green. But: in contrast to the current solution, the change is done as soon as you reach the necessary height difference, while swiping, without releasing the finger. So you see what you WOULD do if you release your finger. If you dont want to do that, move your finger back to the middle to reset to none. Have a look at https://github.com/Birnbaum2001/mapswipe/commits/markAllImprovement. It should give an idea on what I mean :)

**Comment by laurentS** [comment]
@Birnbaum2001 I like the concept of a "preview" of what is about to happen. UX-wise, do you then remove the "undo" swipe up?

On a technical note, I would probably not implement it the way you did in your linked commit: `onToggleTile` triggers a change in the global redux state tree, each of which triggers a rendering of the entire screen (almost all the react components in it, in fact) at that point. Since there are several `handlePanResponderMove` calls per second, you would end up with hundreds of redux state updates during the swipe. On a high end phone, this is probably ok, but on a low end phone, I suspect you might get into an awful lag, or even crash. You can read more on the react component lifecycle and rendering in [the docs](https://reactjs.org/docs/components-and-props.html).

The "results" are in the redux state tree. [Here](http://www.reactnativeexpress.com/redux) is a short intro to the concepts. Implementing a real undo would require storing the previous state for all tiles, and I think it would make the code overly complex, for little user-side added value.

**Comment by jhenshall** [comment]
@Birnbaum2001 @laurentS - also really like the idea of a 'preview' that shows what state will occur if they release their finger. Can't comment on the technicalities of implementing though.

I have had another thought about the whole movement (which would also apply to #127). Thinking it might be nice to make it so the tiles actually move down so the user can see the movement of their downward swipe? Once this has been initiated, horizontal swiping is totally disabled and the user can only swipe up and down. Once they hit the desired amount, the 'preview' comes on and if they release at that point - all tiles marked red/green. If they move finger back to middle, it cancels it.

Sorry, difficult to try and explain. I hope that makes sense? If so, I guess the main question would be is this even possible?! Next I think would be user testing to see which option works best!

**Comment by Birnbaum2001** [comment]
@laurentS : yes: undo would not be there anymore. 
I'm quite new to react, but I thought that the big advantage of react is that it does only rerender if there are changes. And if I set the same state, essentially nothing happens!?

@jhenshall I could try it, but currently, the test server only serves change detection projects.

**Comment by jhenshall** [comment]
@Birnbaum2001 - we added a traditional build area project back in yesterday. Good luck if you're going to give it a try. Look forward to seeing it!

**Comment by forteller** [comment]
I see that this is marked as completed, but I can't see how to do it?
