### ISSUE TITLE
Investigate push notifications - are they working?

### ISSUE THREAD

**Issue by mathcass** [mapswipe/mapswipe#20]

**Comment by russdeffner** [comment]
Looking at the Firebase Cloud Messaging data, it appears we are not doing something right to hit iOS users. Where we are getting at least a few responses from Android each time, going back about a dozen messages, I see zero response from iOS. This is especially troublesome since it shows the message going to about 4 times as many iOS users as Android. Although the last message at least two Android users did not get the message either. Getting messages to all users should be the goal, but if we can just figure out what is wrong with our messaging to iOS it will have a very significant impact on our retention rate and ability to rally swipers.

**Comment by laurentS** [comment]
Closing in favour of #177
