### ISSUE TITLE
Scalebar (for Built Area projects)

### ISSUE THREAD

**Issue by adrienandrem** [mapswipe/mapswipe#46]
While browsing tiles, natural patterns can make you wonder what you are actually looking at.

A scalebar, displayed on the upper border for example, could be really useful.

**Comment by laurentS** [comment]
Thanks for the feedback!

This has been requested by a number of people, and it's been included in the latest design updates. Hoping to get this out to users reasonably soon.

**Comment by rivermont** [comment]
Copied from #111 


Since some projects have slightly different zoom levels, or because of offset and other imagery quirks it can be hard to tell the scale, I think it would be good to include a small ruler in one of the bottom corners of the viewport. Similar to what the iD editor has:

![image](https://user-images.githubusercontent.com/25139386/64914372-f969e180-d71d-11e9-9f82-ffb3d15c4846.png)

It would be overlayed on top of the tiles, but with transparency. Long-pressing the tile under it wouldn't show the scale on the enlarged image.
