### ISSUE TITLE
Can't upload projects - blocked by naming issue

### ISSUE THREAD

**Issue by Katbaloo** [mapswipe/mapswipe#872]
I am trying to upload new projects.  I have tried 3 different options (HOT TM IDs: 9185, 2185).  After attempting to submit, I get the below page reload with "A project with this name already exists"

1. This isn't true - if we are talking about the full string of the name.  I've doubled checked both inactive & finished projects to be sure.
2. IF we are talking about just the Project Topic field we have a problem.  We have shifted so that all project managers should be starting their project names with the type of project, so ever single one should start with Find, Validate, or Compare.

is this happening because of the recent changes to avoid name duplication (with users and with projects?).  if so, we need to adjust how the projects assess because we have to start the name with one of those three words every time.

Or, is something else going on?

![Image](https://github.com/user-attachments/assets/05a7d3bb-fc75-4d78-88d2-74a267bb61b0)

![Image](https://github.com/user-attachments/assets/4613f26f-92ec-4ea0-8ef3-ea07f612e3d0)

**Comment by kopitek8** [comment]
@Katbaloo 

The issue was indeed with the latest update of checking duplicate names. We checked only the topic field when the whole name was supposed to be checked. 

We will update to check the whole of the project name. In this case, the whole string '**Validate - Dedza District, Malawi (1) American Red Cross**' is checked. And if the system already has this string saved, this will **not be allowed**

**Comment by Katbaloo** [comment]
All good!  Appreciate the speedy fix!
